### ISSUE TITLE
One of your answer on Zhihu

### ISSUE THREAD

**Issue by tong-ge** [Cobaltandiron/Crack#3]
At first, they banned WOW, you didn't say anything, because you don't play WOW.
Then they banned Japanese anime, you didn't say anything, because you can still watch them on Youtube.
Then they built the GF Wall, you didn't say anything, because you have the seven sticks.
Then they built the Anti-indulgence, you didn't say anything because you play singleplayer games and external servers by the seven sticks and accelerators.
Finally they burnt the seven sticks, but nobody says anything for you.
![cobaltandiron](https://user-images.githubusercontent.com/40582371/180193661-91dd2ce8-8127-4bc3-b993-5047b65e6f0f.png)

**Comment by JieningYu** [comment]
弱智通哥

**Comment by tong-ge** [comment]
这里你都要来冲

**Comment by JieningYu** [comment]
![image](https://user-images.githubusercontent.com/61787533/201102421-ea13f1e7-4705-4842-89da-8fc1d51e5dc8.png)

**Comment by JieningYu** [comment]
评价为：纯纯的闪天
